### PR TITLE
fix: Change to BSON serialization for public 3rd party

### LINKED ISSUE #51: Store 3rd party endpoint data in a binary format
Follow-up to #50: Use BSON or something else that's binary and doesn't require base64 encoding, instead of JSON.

### PR DESCRIPTION
**Pull request by sdsantos**
Closes #51

### CODE REVIEW

File: lib/src/main/java/tech/relaycorp/relaydroid/endpoint/ThirdPartyEndpoint.kt [hunk 1]
```diff
@@ -109,28 +111,38 @@ public class PublicThirdPartyEndpoint(
...
+            try {
+                val output = BasicOutputBuffer()
+                BsonBinaryWriter(output).use {
+                    it.writeStartDocument()
+                    it.writeString("public_address", publicAddress)
+                    it.writeBinaryData("identity_certificate", BsonBinary(identityCertificate.serialize()))
+                    it.writeEndDocument()
+                }
+                return output.toByteArray()
+            } catch (exp: Exception) {
```
Comment (gnarea) [inline lib/src/main/java/tech/relaycorp/relaydroid/endpoint/ThirdPartyEndpoint.kt:125]: Can we use a more specific exception?

File: lib/src/main/java/tech/relaycorp/relaydroid/endpoint/ThirdPartyEndpoint.kt [hunk 2]
```diff
@@ -109,28 +111,40 @@ public class PublicThirdPartyEndpoint(
...
+                        StoredData(
+                            reader.readString("public_address"),
+                            Certificate.deserialize(
+                                reader.readBinaryData("identity_certificate").data
+                            )
+                        ).also {
+                            reader.readEndDocument()
+                        }
+                    }
+                } catch (exp: Exception) {
```
Comment (gnarea) [inline lib/src/main/java/tech/relaycorp/relaydroid/endpoint/ThirdPartyEndpoint.kt:145]: ditto

**Review by gnarea — CHANGES_REQUESTED** [review]

**Review by gnarea — APPROVED** [review]
